### PR TITLE
[Fix] includes

### PR DESCRIPTION
**Pull request by floriantschopp**
Some small fixes to includes, I am not sure why this even passed CI before tbh...

### CODE REVIEW

**Review by filippobrizzi — APPROVED** [review]

**Review by lhruby — APPROVED** [review]
Interesting. Are we using different compilers? gcc vs clang?

**Comment by floriantschopp** [comment]
> Interesting. Are we using different compilers? gcc vs clang?

same compiler `clang++-18`, the previus shouldn't have compiled as it only included `<string>`, `std::transform` is not part of that...

**Comment by lhruby** [comment]
I'm mainly wondering about `toupper` vs using the lambda you added. It compiled locally and in CI.

**Comment by floriantschopp** [comment]
> I'm mainly wondering about `toupper` vs using the lambda you added. It compiled locally and in CI.

I got
```
stl_algo.h(4252, 5): Candidate template ignored: couldn't infer template argument '_UnaryOperation'
```

**Pull request merged**
