### PR TITLE
Fix some IWYU issues; fix typo in README.

### PR DESCRIPTION
**Pull request by hzeller**
# Description

  * Fix some missing includes to make things compile; it looks like there might be other instances where more diligence is needed w.r.t IWYU, but these I stumbled upon as it made the compile hick-up.
  * The `ninja checks` in the README should really be `check`
  * There is another typo in the README `cmake --preset preferred` ... the `preferred` preset does not actually exist. Maybe `default` was meant ? Anyway, not touching that, but you should probably change that to one of the existing options.

### CODE REVIEW

**Comment by filippobrizzi** [comment]
@hzeller Thanks a lot for your contribution!
You are right, `preferred` is now `default`, I will update the readme.

After your comment, I found that there is this tool [include-what-you-use](https://github.com/include-what-you-use/include-what-you-use) (which you probably know) and I integrated it in the repo https://github.com/olympus-robotics/hephaestus/pull/99, although I still need to understand the proper configuration for it.

**Review by filippobrizzi — APPROVED** [review]

**Comment by hzeller** [comment]
Since you're using `clang-tidy` in the project, enabling the `misc-include-cleaner` check might already provide a bunch of detection without having to use include-what-you-use.

Also the clang layering check is helpful, there are a few options that help keeping include dependencies clean: https://maskray.me/blog/2022-09-25-layering-check-with-clang

**Comment by filippobrizzi** [comment]
Thanks for the tip `misc-include-cleaner` provided to be more helpful than `include-what-you-use`

I have enabled it for the repo and found a lot of missing includes https://github.com/olympus-robotics/hephaestus/pull/107

**Comment by hzeller** [comment]
Cool!

**Pull request merged**
